server:
  port: 8080
spring:
 

  datasource:
    password: Nitesh
    username: root
    url: jdbc:mysql://localhost:3306/egalaxy?characterEncoding=utf8&useUnicode=true&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
      
     

  kafka:
    bootstrap-servers: localhost:9092
    producer:
     
      retries: 3
      batch-size: 16384 
      buffer-memory: 33554432 
      acks: all
    
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      
      group-id: TestGroup
      
      enable-auto-commit: false
     
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
  
      ack-mode: manual_immediate



project:
#  filepath: /root/project/mallProject/backend/files
  filepath: D:\PROJECT GROUP_1\mall\mall\src\main\resources\upload
 #filepath: D:\Gaming Zone\e-commerce-mall-main\MALLL\mall\src\main\resources\upload

